services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    volumes:
      - ./app-data:/app-data
    labels:
      caddy: wiki.rockag.net
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true